### ISSUE TITLE
how to write a condition 

### ISSUE THREAD

**Issue by rifaterdemsahin** [solidify/vsts-task-fail#1]
can we specify if the previous or x task has not fully completed?

**Comment by jesfer** [comment]
In theory yes. In practice... Maybe. It all hinges on if you can write a powershell command to check the outcome of previous task. If so, you can also rework that command into a powershell statement that evaluates to true or false and use that statement as the condition to fail.

Also, I am not sure what the max length for input strings are. It might turn out your statement is too long.

Might be better to just use the built in Powershell task and run the necessary commands there.
