### ISSUE TITLE
Support TFS API v2.3

### ISSUE THREAD

**Issue by icnocop** [solidify/vsts-task-fail#2]
Hi.

Thank you for the VSTS Fail Task.

I'm running TFS 2015 Update 4 and I get the following error when I try to upload the extension:
```
Unable to publish extension due to:
- Incompatible API version (3.0)
```

Is there a specific reason why this extension requires TFS API v3 and isn't backward compatible with a previous version?

From [vss-extension.json#L17](https://github.com/solidify/vsts-task-fail/blob/8d8026dfa52a17a0a933ccd441679d1332478a10/src/vss-extension.json#L17)
```
"demands": [
      "api-version/3.0"
]
```

TFS 2015 Update 4 is v2.3, according to [API and TFS version mapping](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0#api-and-tfs-version-mapping).

Thank you.

**Comment by jesfer** [comment]
Hi,

we'll have a look. This might very well be a remnant of something autogenerated…

**Comment by MOlausson** [comment]
Removed the unnecessary demand, v1.1.2 is rolling out now so have a look @icnocop.

**Comment by icnocop** [comment]
Thank you. It worked! 😄

**Comment by MOlausson** [comment]
Happy it did. And thanks for the feedback!
